name: NodeJS with Gulp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build-assets
        git config user.email "steven.woolston@gmail.com"
        git config user.name "Automation Bot"
        cd ./dist/css
        git add .
        cd ../js
        git add .
        git commit -am "Commiting assets built by gulp"

